version: '3'
services:

  container_a:
    image: tariksalay/container_a:latest
    environment:
      INTERVAL: 300
    depends_on:
      - container_c
    restart: on-failure

  container_b:
    image: tariksalay/container_b:latest
    ports:
      - "8080:5000"
    depends_on:
      - container_a
      - container_c

  container_c:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

