#FROM ubuntu:latest
#LABEL authors="Tarik Salay"
#
#ENTRYPOINT ["top", "-b"]

# Dockerfile to create the image
# There are images ready to use in DockerHub for common services such as PostgreSQL etc.

# Image
FROM rabbitmq:3-management

# Directory
WORKDIR /app
